- name: Run invoice script and package output
  run: |
    mkdir -p outputs
    TIMESTAMP=$(date +"%Y%m%d%H%M%S")
    OUTPUT_CSV="outputs/myoutput_${TIMESTAMP}.csv"
    ZIP_FILE="outputs/invoice_output_${TIMESTAMP}.zip"

    echo "Processing input and saving output as $OUTPUT_CSV"
    python main5.py --input 35.2-40k.csv --output $OUTPUT_CSV

    echo "Listing outputs directory to verify file was created:"
    ls -l outputs/

    echo "Packaging output as ZIP file"
    zip -j $ZIP_FILE $OUTPUT_CSV

    echo "::set-output name=zip-file::$ZIP_FILE"
